
apiVersion: v1
kind: Service
    
metadata:
    name: bull-exporter
    labels:
      app: bull
      role: exporter
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '9538'
spec:
    type: ClusterIP
    ports:
    - name: bullexporter
      port: 9538
      targetPort: 9538
    selector:
      app: bull
      role: exporter
    