
apiVersion: v1
kind: Service
    
metadata:
    name: bull-exporter
    labels:
      app: bull
      role: exporter
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '5959'
spec:
    type: ClusterIP
    ports:
    - name: http
      port: 5959
      targetPort: 5959
    selector:
      app: bull
      role: exporter
    